### ISSUE TITLE
Issues in replicating example results

### ISSUE THREAD

**Issue by yanyul233** [sayangsep/Beatrice-Finemapping#1]
Hi! I'm having issues to reproduce the example results (`results/`). I used the command as suggested in the readme:
```
python beatrice.py --z example_data/Simulation_data0.z --LD example_data/Simulation_data0.ld \
  --N 5000  --target test
```
The PIPs are different from the ones in `results/pip.csv`.

**Comment by sayangsep** [comment]
It’s probably because BEATRICE learns set of parameters that get initialized differently across systems. If you plot and check the pip values they should be close. Another reason could be the uploaded pips have not been updated. I would say you generate the pips and check for the plots to see any inconsistencies.

**Comment by yanyul233** [comment]
Hi @sayangsep, 

Thanks for your reply! 
Here is the comparison of PIPs between `results/pip.csv` and my test
![pip_comparison](https://github.com/user-attachments/assets/b5e8fa8a-78e1-47b7-8ad7-defd060fef98)
So, some of the variants are having a bigger diff.

Moreover, the credible sets reported look a bit off in my test:
```
$ cat test/credible_set.txt
818
293
407
832
726
122
505
$ cat test/conditional_credible_variants_probability.txt
1.0
0.999
0.508
0.504
0.504
0.502
0.875
```
As you can see there are CSs with quite small cumulative PIPs whereas the default should be 0.95? 

Thanks!

**Comment by yanyul233** [comment]
For your reference, here are the CSs from `results/`
```
$ cat results/credible_set.txt
818
293
407 290 505
597 286 726
122 995 45 590
832 820 702 700 219
$ cat results/conditional_credible_variants_probability.txt
1.0
0.986
0.78 0.168 0.154
0.682 0.205 0.197
0.562 0.154 0.154 0.152
0.478 0.135 0.133 0.133 0.133
```

**Comment by sayangsep** [comment]
Looks like the uploaded results are from an older version. I need to update it.  But you can probably see that the snps present in your credible set are also present in results/credible_set.txt. To answer your second question: yes, the coverage is set at 0.95 but Beatrice also has a parameter gamma_selection that doesn’t add snps if the probability of the snp being present in the credible set is < threshold. This ensure that you don’t fill your credible set with spurious snps. You can reduce gamma_selection and get bigger credible sets.

**Comment by yanyul233** [comment]
Hi @sayangsep, thanks for the explanation. May I ask what is the ground truth of the example data (i.e. the causal variants and effect sizes). I noticed that similar variants were captured in both my results and `results/` but my concern is specifically about variant 407 and 505 where in the old result, they were in one credible set but now that they are considered as two causal signals.

**Comment by sayangsep** [comment]
Hi @yanyul233,
Unfortunately, I do not have the raw data from which I generated the results. However, I have updated the example_data folder with a new set of simulation data and results. Please let me if you still face similar issues. I have also uploaded the causal locations and the effect sizes in separate files.

**Comment by yanyul233** [comment]
Hi @sayangsep, now that the results look good to me. Thank you! I will close this issue.

**Comment by sayangsep** [comment]
Great.
